### ISSUE TITLE
"implement 'authorization_code' and work like the..."

### ISSUE THREAD

**Issue by vangorra** [RocketChat/rocketchat-oauth2-server#1]
Where is one suppose to implement authorization_code? There doesn't appear to be any callbacks or database hooks.

**Comment by rodrigok** [comment]
Sorry, can you explain better?

**Comment by vangorra** [comment]
I don't know what that sentence is trying to say. I read it as a command to the consumer of the package to implement specific functionality in order to get things working.

**Comment by rodrigok** [comment]
Oh, ok, sorry about that, I just fixed the README with the correct sentence.

`It implements the athorization_code and works like the Facebook's OAuth popup.`

Is it clear now?

**Comment by vangorra** [comment]
Ahh.. That makes so much more sense.

**Comment by rodrigok** [comment]
:smile: as you can see, I'm not fluent in English

Thanks
