### ISSUE TITLE
Error: has no method 'authorize'

### ISSUE THREAD

**Issue by anti1234** [RocketChat/rocketchat-oauth2-server#3]
Hi, I got this error while I run the example showed on README. 

```
TypeError: Object [object Object] has no method 'authorize'
W20160304-16:16:35.383(8)? (STDERR)     at server/oauth2server.js:21:56
W20160304-16:16:35.383(8)? (STDERR)     at /home/ljm/simple-todos/.meteor/local/build/programs/server/app/server/oauth2server.js:39:4
W20160304-16:16:35.383(8)? (STDERR)     at /home/ljm/simple-todos/.meteor/local/build/programs/server/boot.js:242:10
W20160304-16:16:35.383(8)? (STDERR)     at Array.forEach (native)
W20160304-16:16:35.383(8)? (STDERR)     at Function._.each._.forEach (/root/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160304-16:16:35.384(8)? (STDERR)     at /home/ljm/simple-todos/.meteor/local/build/programs/server/boot.js:137:5
```

It seems this error is  caused by this  function:

```
oauth2server.routes.get('/account', oauth2server.oauth.authorize(), function(req, res, next) {
  var user = Meteor.users.findOne(req.user.id);

  res.send({
    id: user._id,
    name: user.name
  });
});
```

I am so confused that `authorize` has been implemented by `node-oauth2-server` , why the error  occurred ?

:laughing:  So so appreciate for any idea !

**Comment by anti1234** [comment]
Well, it works when I change  the `authorize()` to `authorise()` .  

Then I check the code download from `npm install oauth-server` .  It is different from [node-oauth2-server](https://github.com/thomseddon/node-oauth2-server)

:laughing:  Whatever, it works now .

**Comment by engelgabriel** [comment]
Thanks for point our the inconsistency.

Please @rodrigok can we do a global search and replace on the repo to fix this?

**Comment by rodrigok** [comment]
Fixed via https://github.com/RocketChat/rocketchat-oauth2-server/commit/5f3904edb7a9c3eb0fd4a34f643ef6a2623bb9a4?ts=2
